### ISSUE TITLE
Status indicator for the running test

### ISSUE THREAD

**Issue by deanfourie1** [iitggithub/iperf-web#4]
A little progress bar or status indicator to show that the test is running might be a nice touch :). Nice app thanks!

Also, the ability to save servers for future testing would be nice too. An option to save server that you can then select for a drop down and it saves the port and host address.

**Comment by iitggithub** [comment]
Sounds like a great idea. I'll see what i can come up with.

**Comment by iitggithub** [comment]
Since this is two requests, i've split out the second request into its own issue. https://github.com/iitggithub/iperf-web/issues/5

**Comment by iitggithub** [comment]
You should be able to pull down the latest version of the container and see the little loading widget appear next to the Run Test button
